### ISSUE TITLE
D2 Shard

### ISSUE THREAD

**Issue by Shwasx** [M7ilan/D2-Legendary-Shard#1]
Hello M7ilan,
Scripts almost works perfect, just for some of us, mouse is 0.5-1 cm of when picking up item. (dunemarchers)
![bild_2023-05-26_212328023](https://github.com/M7ilan/D2-Legendary-Shard/assets/134736202/b2d5f610-f662-4aba-a5e0-4436c5889760)
Just like this, I have followed instructions of windows and in game resolution size.

**Comment by M7ilan** [comment]
> Hello M7ilan,
> 
> Scripts almost works perfect, just for some of us, mouse is 0.5-1 cm of when picking up item. (dunemarchers)
> 
> ![bild_2023-05-26_212328023](https://github.com/M7ilan/D2-Legendary-Shard/assets/134736202/b2d5f610-f662-4aba-a5e0-4436c5889760)
> 
> Just like this, I have followed instructions of windows and in game resolution size. 


The glitch has just been patched. However, the problem occurred because your screen may be small, causing the text above the item to push the item slightly towards the bottom. To fix this, try editing the code in the ‘MouseMove’, specifically on the Y-axis.
